### ISSUE TITLE
Error with new 'banner' functionality when parsing nmap scan results

### ISSUE THREAD

**Issue by hotpheex** [ChrisRimondi/VulntoES#14]
![image](https://user-images.githubusercontent.com/30642540/34474005-7a5291be-efcd-11e7-97ee-7b9f527c970e.png)

**Comment by redxking** [comment]
I am getting the same issue.. Any one know how to fix this?

**Comment by uhhhhhwat** [comment]
Yep, same issue for me.
`null@ubuntu:~VulntoES$ python VulntoES.py -i 10_windows_version_scan.xml -e 127.0.0.1 -r nmap -I nmap-vuln-to-es
Sending Nmap data to Elasticsearch
Traceback (most recent call last):
  File "VulntoES.py", line 433, in <module>
    main()
  File "VulntoES.py", line 424, in main
    np.toES()
  File "VulntoES.py", line 216, in toES
    if p.attrib['banner']:
KeyError: 'banner'
null@ubuntu:~/VulntoES$ `

**Comment by fluidum** [comment]
#                                                                        if p.attrib['banner']:
#                                                                           dict_item['banner'] = p.attrib['banner']

I commented out those two lines and nmap XML push was successful to Elastic.
