### ISSUE TITLE
Error on sending data to Elasticsearch

### ISSUE THREAD

**Issue by dkade** [ChrisRimondi/VulntoES#3]
Hey man, I have this problem, running debian wheezy python 2.7:

Sending Nessus data to Elasticsearch
Traceback (most recent call last):
  File "./VulntoES.py", line 378, in <module>
    main()
  File "./VulntoES.py", line 361, in main
    np.toES()
  File "./VulntoES.py", line 122, in toES
    self.es.index(index=self.index_name,doc_type="vuln", body=json.dumps(dict(host_item.items()+dict_item.items())))
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 251, in index
    raise ValueError("Empty value passed for a required argument.")
ValueError: Empty value passed for a required argument.

**Comment by dkade** [comment]
Found the issue, was not passing -I in the line with the mapping as you do not have it on your blog post: http://www.securitygrit.com/2014/05/vulnerability-data-into-elasticsearch.html

Solved! :) thank you

**Comment by dkade** [comment]
Solved! :) thank you

**Comment by kmontalto** [comment]
Hi, I'm curious how you fixed this, I downloaded this script and am getting the same error. I'm new to python so looking for some help. Thanks

**Comment by kmontalto** [comment]
never mind, figured it out!
